### ISSUE TITLE
[BUG] won't run with "NoClassDefFoundError" might be aarch64 related

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/exist-xqts-runner#20]
brand new system, everything starting from scratch:
Steps: 
- [x] Clone and build exist develop branch (java8)
- [x] clone xqts runner
- [x] build: `sbt clean assembly`
   ```
   [success] Total time: 6 s, completed Nov 17, 2021 3:56:58 PM
   ```
- [] run: `target/scala-2.13/exist-xqts-runner-assembly-1.0.0.jar -x HEAD`
   ```
   Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at grizzled.slf4j.Logger$.apply(slf4j.scala:418)
	at grizzled.slf4j.Logger$.apply(slf4j.scala:427)
	at org.exist.xqts.runner.XQTSRunner.<init>(XQTSRunner.scala:256)
	at org.exist.xqts.runner.XQTSRunner$.main(XQTSRunner.scala:240)
	at org.exist.xqts.runner.XQTSRunner.main(XQTSRunner.scala)
   Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 5 more
   ```

Also tried `sbt run` same errors

Java + maven (OS): 
```
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: /opt/homebrew/Cellar/maven/3.8.3/libexec
Java version: 1.8.0_312, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "12.0.1", arch: "aarch64", family: "mac"
```
sbt + scala
```
[info] welcome to sbt 1.5.5 (Azul Systems, Inc. Java 1.8.0_312)
Scala code runner version 2.13.7
```

**Comment by line-o** [comment]
@duncdrum could you retest with current develop?

**Comment by duncdrum** [comment]
it runs again from within core.
