### ISSUE TITLE
eXist 5.0.0 compatibility

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist-xqts-runner#7]
Running `sbt compile` with `build.sbt` line 17-18 changed to:

```scala
  val existV = "5.0.0"
  //val existV = "20180712"
```

... ends in the following error:

```text
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.exist-db#exist-testkit;5.0.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.exist-db:exist-testkit:5.0.0 (/Users/joe/workspace/exist-xqts-runner/build.sbt#L16-40)
[warn] 		  +- org.exist-db:exist-xqts-runner_2.12:1.0.0
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.exist-db#exist-testkit;5.0.0: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2386)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: org.exist-db#exist-testkit;5.0.0: not found
[error] Total time: 39 s, completed Nov 4, 2019 9:30:52 AM
```

**Comment by joewiz** [comment]
Commenting out line 31 to read:

```
    //"org.exist-db" % "exist-testkit" % existV,
```

... allows the compilation to complete without error:

```bash
$ sbt compile
[info] Loading settings from assembly.sbt,license.sbt,header.sbt,plugins.sbt ...
[info] Loading project definition from /Users/joe/workspace/exist-xqts-runner/project
[info] Loading settings from build.sbt ...
[info] Set current project to exist-xqts-runner (in build file:/Users/joe/workspace/exist-xqts-runner/)
[info] Executing in batch mode. For better performance use sbt's shell
[warn] Credentials file /Users/joe/.ivy2/.credentials does not exist
[info] Updating ...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* junit:junit:4.12 is selected over 3.8.1
[warn] 	    +- org.apache.ant:ant-junit:1.10.4                    (depends on 3.8.1)
[warn] 	    +- org.apache.ws.commons.util:ws-commons-util:1.0.2   (depends on 3.8.1)
[warn] 	    +- org.exist-db:exist-core:5.0.0                      (depends on 3.8.1)
[warn] 	    +- org.exist-db:exist-xqts-runner_2.12:1.0.0          (depends on 3.8.1)
[warn] 	* xml-apis:xml-apis:1.4.01 is selected over 1.0.b2
[warn] 	    +- org.exist-db.thirdparty.xerces:xercesImpl:2.12.0   (depends on 1.4.01)
[warn] 	    +- org.exist-db:exist-core:5.0.0                      (depends on 1.4.01)
[warn] 	    +- org.apache.ws.commons.util:ws-commons-util:1.0.2   (depends on 1.0.b2)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 18 Scala sources to /Users/joe/workspace/exist-xqts-runner/target/scala-2.12/classes ...
[warn] there was one deprecation warning (since 2.11.0); re-run with -deprecation for details
[warn] there were 7 feature warnings; re-run with -feature for details
[warn] two warnings found
[info] Done compiling.
[success] Total time: 29 s, completed Nov 4, 2019 9:53:11 AM
```

**Comment by duncdrum** [comment]
yes testkit is no more

**Comment by joewiz** [comment]
Running the compiled package ends with the CPU pegged for >30 min, requiring a force kill:

```
[INFO] [11/04/2019 10:34:39.493] [XQTSRunnerSystem-akka.actor.default-dispatcher-15] [akka://XQTSRunnerSystem/user/XQTSRunner/TestCaseRunnerRouter/$g] Message [org.exist.xqts.runner.TestCaseRunnerActor$RunTestCaseInternal] from Actor[akka://XQTSRunnerSystem/user/XQTSRunner/TestCaseRunnerRouter/$g#-1520839674] to Actor[akka://XQTSRunnerSystem/user/XQTSRunner/TestCaseRunnerRouter/$g#-1520839674] was not delivered. [99] dead letters encountered, no more dead letters will be logged. If this is not an expected behavior, then [Actor[akka://XQTSRunnerSystem/user/XQTSRunner/TestCaseRunnerRouter/$g#-1520839674]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
SYSTEM INFO
Database instance: exist
-------------------------------------------------------------------

[WARN] [11/04/2019 10:34:49.360] [XQTSRunnerSystem-shutdown-hook-1] [CoordinatedShutdown(akka://XQTSRunnerSystem)] CoordinatedShutdown from JVM shutdown failed: Futures timed out after [10000 milliseconds]
[WARN] [11/04/2019 10:34:49.534] [XQTSRunnerSystem-akka.actor.default-dispatcher-15] [CoordinatedShutdown(akka://XQTSRunnerSystem)] Coordinated shutdown phase [actor-system-terminate] timed out after 10000 milliseconds
04 Nov 2019 10:37:45,321 [BrokerPools-ShutdownHook] WARN  (BrokerPool.java [shutdown]:1586) - Not all threads returned. Forcing shutdown ... 
Killed: 9
$ date
Mon Nov  4 11:06:01 EST 2019
```

Attached is the full log: [2019-11-04-joes-xqts-log-01.txt](https://github.com/eXist-db/exist-xqts-runner/files/3804866/2019-11-04-joes-xqts-log-01.txt)

**Comment by adamretter** [comment]
@joewiz I have updated this for eXist 5.0.0 now. I think it still is not quite right, but maybe you will get further...

**Comment by joewiz** [comment]
@adamretter As I mentioned the other day in Slack, your change allowed me to build the current master branch, but running the test suite runner, it crashes part way through:

```
08 Nov 2019 10:02:19,058 [XQTSRunnerSystem-akka.actor.default-dispatcher-22] INFO  (slf4j.scala [info]:159) - Serialized results for TestSet: fn-distinct-values OK. 
Exception in thread "global.BrokerPools.ShutdownHook" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at org.exist.storage.ProcessMonitor.killAll(ProcessMonitor.java:305)
	at org.exist.storage.BrokerPool.shutdown(BrokerPool.java:1610)
	at org.exist.storage.BrokerPools.stopAll(BrokerPools.java:281)
	at org.exist.storage.BrokerPools.lambda$0(BrokerPools.java:69)
	at java.lang.Thread.run(Thread.java:748)
```

This is on macOS 10.15.1 with Java 1.8.0_232 (Zulu 8.42.0.21-CA-macosx).

(Just pasting in my results here so they aren't lost in Slack history.)

Also, for anyone else, when the junit results are turned into a report (presumably this would happen automatically when the test suite finishes; but if yours crashes too, you can create the report manually via `ant -f create-report.xml`), you need to change the directory path in https://github.com/eXist-db/exist-xqts-runner/blob/master/create-report.xml#L13 to point to your eXist location, e.g., `/Users/joe/workspace/exist/exist-distribution/target/exist-distribution-5.1.0-SNAPSHOT-dir/lib`.

**Comment by adamretter** [comment]
This is now fixed in - https://github.com/eXist-db/exist-xqts-runner/pull/9
